---
abstract: 'The web service creation framework written with events in mind.'
author:
  - 'Igor Zinovyev <zinigor@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eve
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Session: 0
  Contextual::Return: 0
  DBD::Pg: 0
  DateTime: 0
  DateTime::Format::HTTP: 0
  DateTime::Format::Pg: 0
  Email::Sender::Simple: 0
  Exception::Class: 0
  Hash::MultiValue: 0
  JSON::XS: 0
  PadWalker: 0
  Plack::Request: 0
  Template: 0
  Test::Class: 0
  Test::MockObject: 0
  Test::More: 0
  Tie::IxHash: 0
  URI: 0
version: 0.06
